[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/vektah/gqlparser"

[prune]
  go-tests = true
  unused-packages = true
